[package]
name = "dino-park-fence"
version = "0.2.0"
authors = ["Florian Merz <me@fiji-flo.de>"]
edition = "2018"

[features]
default = []
localuserscope = ["dino_park_gate/localuserscope"]

[dependencies]
cis_client = { git = "https://github.com/mozilla-iam/cis_client-rust", branch = "0.7", version = "0.7", features = ["sync"] }
cis_profile = { git = "https://github.com/mozilla-iam/cis_profile-rust", branch = "0.4", version = "0.4", features = ["aws", "vendored", "graphql"] }
dino_park_gate = { git = "https://github.com/mozilla-iam/dino-park-gate", tag = "0.7.2", version = "0.7.2" }
dino_park_trust = { git = "https://github.com/mozilla-iam/dino-park-trust", tag = "0.0.7", version = "0.0.7" }
dino_park_guard = { git = "https://github.com/mozilla-iam/dino-park-guard", tag = "0.2.3", version = "0.2.3" }
actix-web = "2.0"
actix-rt = "1.0"
actix-http= "1.0"
juniper = "0.14"
futures = "0.3"
log = "0.4"
env_logger = "0.7"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = { version = "0.10", features = ["blocking"] }
chrono = "0.4"
biscuit = "0.4"
percent-encoding = "2.1"
config = "0.10"
failure = "0.1"
url = "2.1"
prometheus = { version = "0.9", default-features = false }
