[env]
DP_AUTH = "https://dev.mozilla-dev.auth0.com/"
DP_DINO_PARK__FOSSIL__UPLOAD_ENDPOINT = ""
DP_DINO_PARK__LOOKOUT__INTERNAL_UPDATE_ENABLED = "false"
DP_DINO_PARK__LOOKOUT__INTERNAL_UPDATE_ENDPOINT = ""
DP_DINO_PARK__ORGCHART__FULL_ENDPOINT = ""
DP_DINO_PARK__ORGCHART__RELATED_ENDPOINT = ""
DP_DINO_PARK__ORGCHART__TRACE_ENDPOINT = ""
DP_DINO_PARK__SEARCH__SIMPLE_ENDPOINT = ""
AWS_DEFAULT_REGION = "us-west-2"
