---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dino-park-nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx-{{ .Values.namespace }}"
    ingress.kubernetes.io/limit-rps: "1000"
    cert-manager.io/issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Frame-Options: DENY" "X-XSS-Protection: 1" "X-Content-Type-Options: nosniff" "Strict-Transport-Security: max-age=63072000" "Content-Security-Policy: default-src 'none'; connect-src 'self'; font-src https://fonts.gstatic.com; img-src 'self' data: blob:; script-src 'self' 'sha256-4qKuKHlhZHVtOHkzV6IoRxvJyftFsU9Bzug8piLac2s=' 'sha256-wFlxiON/IU9ZZ5PD6RqOAhUMQtTTYSO6Fh/5V470Tdo='; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'; manifest-src 'self'; prefetch-src 'self'";
spec:
  tls:
  - hosts:
    - {{ .Values.domain_name }}
    {{- with .Values.secondary_domain_name }}
    - {{ . }}
    {{- end }}
    secretName: dino-park-secret
  rules:
  - host: {{ .Values.domain_name }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: public-splitter
            port:
              number: 80
      - path: /oauth/callback
        pathType: ImplementationSpecific
        backend:
          service:
            name: gatekeeper
            port:
              number: 80
  {{- with .Values.secondary_domain_name }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: public-splitter
            port:
              number: 80
  {{- end }}
