name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust 1.46.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.60.0
          override: true
          components: rustfmt, clippy
    - name: FMT
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all --all-features -- -D warnings
    - name: Build
      run: cargo build --all --all-features --verbose
    - name: Run tests
      run: cargo test --all --all-features
